-- NOTE: reminder_preferences and reminder_logs tables were already created
-- in migration 20260217164516. This migration originally recreated them
-- without IF NOT EXISTS, causing errors on fresh deploys. Replaced with
-- a no-op to keep the migration history intact.
